In [1]:
import numpy as np

In [41]:
def apply_mask(ımg, kernel, index_x, index_y):
    slice_ımg = ımg[index_y:index_y + len(kernel),index_x:index_x + len(kernel)]
    return (slice_ımg * kernel).sum()

def convolve(ımg, kernel):
    _list = []
    for i in range(len(ımg) - len(kernel) + 1):
        for j in range(len(ımg) - len(kernel) + 1):
            _list.append(apply_mask(ımg, kernel, j, i))
    return np.array(_list).reshape(len(kernel),len(kernel))

def relu(array):
    return (np.maximum(0,array))            

def max_pool(array):
    _list = []
    for i in range(len(array) - 1):
        for j in range(len(array) - 1):
            _list.append(max((array[i:i+2,j:j+2]).flatten()))
    return np.array(_list).reshape(len(array)-1,len(array)-1)

max_pool(relu(convolve(array,kernel)))

array([[405,  45],
       [365,  45]])

In [30]:
array=np.array([[50,110,180,130,60],
                [55,115,190,120,50],
                [40,100,180,120,60],
                [30,80,120,100,40],
                [10,70,90,70,10]])

kernel = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])

convolve(array, kernel)

array([[ 405,   45, -380],
       [ 365,   45, -340],
       [ 310,   40, -280]])

array([[ 40, 100, 180],
       [ 30,  80, 120],
       [ 10,  70,  90]])